// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Access tokens allow a user to authenticate against the Pulumi Service
 */
export class MyResource extends pulumi.CustomResource {
    /**
     * Get an existing MyResource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): MyResource {
        return new MyResource(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'myprovider:index:MyResource';

    /**
     * Returns true if the given object is an instance of MyResource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MyResource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MyResource.__pulumiType;
    }

    /**
     * Description of the access token.
     */
    public readonly description!: pulumi.Output<string | undefined>;

    /**
     * Create a MyResource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MyResourceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.description === undefined) && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
        } else {
            resourceInputs["description"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MyResource.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a MyResource resource.
 */
export interface MyResourceArgs {
    /**
     * Description of the access token.
     */
    description: pulumi.Input<string>;
}
